channels:
  - defaults
  - conda-forge
dependencies:
  - black
  - dask
  - flake8
  - fsspec
  - isort
  - make
  - mdformat
  - mypy = 0.812
  - nomkl
  - numpy >= 1.21.0
  - pip
  - pytest
  - pytest-cov
  - rasterio >= 1.2.4
  - rioxarray
  - xarray >= 0.20.2
  - xmlschema
  - pip:
    - mdformat-gfm
