[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools_scm[toml]>=3.4",
    "setuptools_scm_git_archive",
]

[tool.setuptools_scm]
fallback_version = "999"

[tool.coverage.run]
branch = true
omit = ["setup.py"]

[tool.isort]
profile = "black"