[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools_scm[toml]>=3.4",
    "setuptools_scm_git_archive",
]

[tool.setuptools_scm]
write_to = "xarray_sentinel/version.py"
write_to_template = '''
# don't change, don't track in version control
__version__ = "{version}"
'''

[tool.coverage.run]
branch = true
omit = ["setup.py"]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
addopts = "--doctest-glob='*.md'"
