name: on-push

on: [push, pull_request]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache conda
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key:
            ubuntu-latest-conda-py3.8
      - uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge
          channel-priority: strict
          mamba-version: "*"
          activate-environment: xarray-sentinel-tests
          auto-update-conda: false
          python-version: 3.8
          use-only-tar-bz2: true
      - name: Install conda dependencies
        run: |
          mamba env update -f environment-ci.yml
      - name: Install xarray-sentinel
        run: |
          python -m pip install --no-deps -e .
      - name: Run tests
        run: |
          python -m pytest --cov=. --cov-report=xml .
      - name: Upload code coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          env_vars: RUNNER_OS,PYTHON_VERSION
          name: codecov-umbrella
          fail_ci_if_error: false

      
